### ISSUE TITLE
autotag stalls at HDX

### ISSUE THREAD

**Issue by mubix** [ApertureLabsLtd/RFIDler#29]
It just stalls and never finishes

Current version: 0187-beta
```
RFIDler> version
0187-beta
RFIDler> autotag
  ASKRAW: 9<removed data>
  FSK1RAW: 
  FSK2RAW: 
  PSK1RAW: 
  PSK2RAW: 
  PSK3RAW: 
  HITAG1: 
  HITAG2: 
  EM4X02: 
  Q5: 
  HID26: 
  INDALA64: 
  INDALA224: 
  UNIQUE: 
  FDXB: 
  T55X7: 
  AWID26: 
  EM4X05: 
  TAMAGOTCHI: 
  HDX: 

```
